### ISSUE TITLE
Maquetación de la vista: Gestión de Cursos

### ISSUE THREAD

**Issue by wilmer990413** [MAKAIABootcamp/gestaCourse-project-frontend-6#13]
Yo como desarrollador requiero construir la maquetación de la sección de Gestión de Cursos para tener la base inicial de esta vista.
 - [x] Crear rama en el proyecto
 - [x] Crear archivos en proyecto de React
 - [x] Construir la maquetación de la vista de acuerdo al modelo entregado
 - [x] Subir cambios en la rama

**Comment by josmanm** [comment]
Falta acomodar la poscion de los botenes de editar y eliminar en la tabla
